#ifndef TRAFFICLIGHTCONTROLLER_SETTINGS_H
#define TRAFFICLIGHTCONTROLLER_SETTINGS_H


//state machine
#define PEDESTRIAN_GREEN 10000
#define PEDESTRIAN_GREEN_EXTENDED 15000
#define CAR_GREEN 5000
#define CAR_RED_YELLOW 3000
#define CAR_GREEN_YELLOW 2000
#define CAR_GREEN_EXTENDED_LOOP 3000
#define EMERGENCY 10000
#define PUBLIC_TRANSPORT 10000
#define PUBLIC_TRANSPOR_TIME_DECREASE 4000

//camera
#define CAMERA_WIDTH 800
#define CAMERA_HEIGHT 600

//misc
#define BUTTON_PRESS_DELAY 2000

#endif //TRAFFICLIGHTCONTROLLER_SETTINGS_H
